/********************************************************************************/
/*                                                                              */
/*              SepalChatGPT.java                                               */
/*                                                                              */
/*      Find patch suggestions using ChatGPT                                    */
/*                                                                              */
/********************************************************************************/

package edu.brown.cs.rose.sepal;

import java.io.File;

import org.eclipse.jdt.core.dom.ASTNode;
import org.eclipse.jdt.core.dom.Statement;
import org.w3c.dom.Element;

import edu.brown.cs.ivy.xml.IvyXmlWriter;
import edu.brown.cs.rose.root.RootControl;
import edu.brown.cs.rose.root.RootEdit;
import edu.brown.cs.rose.root.RootRepairFinderDefault;
import edu.brown.cs.rose.root.RoseLog;

import org.eclipse.text.edits.ReplaceEdit;
import org.eclipse.text.edits.TextEdit;


import chatgpt_repair.ChatgptRepair;

public class SepalChatGPT extends RootRepairFinderDefault
{

/********************************************************************************/
/*                                                                              */
/*      Private Storage                                                         */
/*                                                                              */
/********************************************************************************/

private boolean use_chatgpt = true;

private String api_host = "https://api.openai.com";
private String api_key = "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";



/********************************************************************************/
/*                                                                              */
/*      Processing methods                                                      */
/*                                                                              */
/********************************************************************************/

@Override public double getFinderPriority()
{
   return 0.5;
}



@Override public void process()
{
   if (getProcessor().haveGoodResult() || !use_chatgpt) return;

   RootControl ctrl = getProcessor().getController();
   Statement stmt = (Statement) getResolvedStatementForLocation(null);
   if (stmt == null) return;

   File bfile = getLocation().getFile();
// int lno = getLocation().getLineNumber();
   String bcnts = ctrl.getSourceContents(bfile);

   // get enclosing method
   ASTNode enclosingMethod = stmt.getParent();
   while (enclosingMethod.getNodeType() != ASTNode.METHOD_DECLARATION) {
      enclosingMethod = enclosingMethod.getParent();
   }
   // TODO: How to get the source code of this method? Is this correct?
   String buggy_method = bcnts.substring(enclosingMethod.getStartPosition(),
      enclosingMethod.getStartPosition() + enclosingMethod.getLength());

   // get patch from ChatGPT (one patch per faulty line)
   String patch;
   try {
      // 1: getPatch(buggy_method: String, faulty_stmt_start_index: int, faulty_stmt_length: int, api_host: String, api_key: String)
      // 2: getPatch(buggy_method: String, faulty_stmt_line: int, api_host: String, api_key: String)
      patch = ChatgptRepair.getPatch(buggy_method,
         stmt.getStartPosition() - enclosingMethod.getStartPosition(), stmt.getLength(),
         api_host, api_key);
   }
   catch (com.plexpt.chatgpt.exception.ChatException e) {
      // rate limit
      return;
    }
   catch (Throwable e) {
      RoseLog.logE("SEPAL","Problem with chatgpt",e);
      return;
   }

   // add repair
   // addRepair(edit: Element/ASTRewrite, description: String, logdata: String, priority_score: double)
   // TODO: How to create an edit xml? Is this correct?
   TextEdit te = new ReplaceEdit(stmt.getStartPosition(), stmt.getLength(), patch);
   
   RootEdit redit = new RootEdit(bfile, te);
   Element edit = redit.getTextEditXml();
   addRepair(edit, "generated by ChatGPT", getClass().getName() + "@ChatGPT", 0);
}
}       // end of class SepalChatGPT


/* end of SepalChatGPT.java */
